### PR TITLE
userspace: proxy: Fix typo in variable name

### LINKED ISSUE #10431: [BUG] github tests: build-linux ptl fails to heap_uncached_part failure
**Describe the bug**
Regression in commit 9cc7ad94d1e378c3a2b128178330321d99787dc8

https://github.com/thesofproject/sof/actions/runs/20127912805/job/57761888407?pr=10429

```
 /__w/sof/sof/sof/src/audio/module_adapter/library/userspace_proxy.c: In function 'userspace_proxy_memory_init':
/__w/sof/sof/sof/src/audio/module_adapter/library/userspace_proxy.c:77:18: error: 'heap_part_cached' undeclared (first use in this function)
   77 |                 &heap_part_cached,
      |                  ^~~~~~~~~~~~~~~~
```

Problem uncovered when USERSPACE_PROXY was enabled in a default build target.

### PR DESCRIPTION
**Pull request by softwarecki**
Fix typo in variable name from `heap_part_cached` to `heap_cached_part`.

Fixes #10431

### CODE REVIEW

File: src/audio/module_adapter/library/userspace_proxy.c [hunk 1]
```diff
@@ -74,7 +74,7 @@ static int userspace_proxy_memory_init(struct userspace_context *user,
 
 	struct k_mem_partition *parts_ptr[] = {
 #ifdef HEAP_PART_CACHED
```
Comment (lgirdwood) [inline src/audio/module_adapter/library/userspace_proxy.c:76]: Can we align the Kconfig name in a subsequent PR?  It seems like a copy paste type issue.

**Comment by kv2019i** [comment]
Known issue seen https://sof-ci.01.org/sofpr/PR10432/build17976/devicetest/index.html?model=PTLP_RVP_SDW&testcase=verify-kernel-boot-log . One new in https://sof-ci.01.org/sofpr/PR10432/build17976/devicetest/index.html but this seems to be a DUT specific issue, not related to this PR. Proceeding with merge.
