### ISSUE TITLE
[BUG] github tests: build-linux ptl fails to heap_uncached_part failure

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#10431]
**Describe the bug**
Regression in commit 9cc7ad94d1e378c3a2b128178330321d99787dc8

https://github.com/thesofproject/sof/actions/runs/20127912805/job/57761888407?pr=10429

```
 /__w/sof/sof/sof/src/audio/module_adapter/library/userspace_proxy.c: In function 'userspace_proxy_memory_init':
/__w/sof/sof/sof/src/audio/module_adapter/library/userspace_proxy.c:77:18: error: 'heap_part_cached' undeclared (first use in this function)
   77 |                 &heap_part_cached,
      |                  ^~~~~~~~~~~~~~~~
```

Problem uncovered when USERSPACE_PROXY was enabled in a default build target.

**Comment by kv2019i** [comment]
Can you take a look? This is visible in every PR now.
