### ISSUE TITLE
[BUG] base_fw.c:686:3: error: label followed by a declaration is a C23 extension

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#10527]
**Describe the bug**
Build regression in https://github.com/thesofproject/sof/pull/10523

Logs:
https://github.com/thesofproject/sof/actions/runs/21713822303/job/62624107831
