### PR TITLE
topology2: intel: bt-ssp-config: use cardinal clock as source

### PR DESCRIPTION
**Pull request by plbossart**
All existing SSP-based topologies use the audio cardinal clock, *EXCEPT* Bluetooth related ones. This doesn't make much sense, let's use the same clock source for all SSPs.

### CODE REVIEW

**Comment by plbossart** [comment]
@kv2019i @ranj063 @naveen-manohar @sathyap-chrome @sathya-nujella @Vamshigopal @RDharageswari please chime in

**Comment by plbossart** [comment]
Looks like the build is broken, there's no way a topology2 change could cause a build issue in the fuzzer

https://github.com/thesofproject/sof/actions/runs/6223015308/job/16888062822?pr=8214

````
FAILED: zephyr/zephyr.elf zephyr/zephyr_pre0.map zephyr/zephyr.map zephyr/zephyr.lst zephyr/zephyr.stat zephyr/zephyr.strip zephyr/zephyr.exe /home/runner/work/sof/sof/workspace/build-fuzz/zephyr/zephyr_pre0.map /home/runner/work/sof/sof/workspace/build-fuzz/zephyr/zephyr.map /home/runner/work/sof/sof/workspace/build-fuzz/zephyr/zephyr.lst /home/runner/work/sof/sof/workspace/build-fuzz/zephyr/zephyr.stat /home/runner/work/sof/sof/workspace/build-fuzz/zephyr/zephyr.strip /home/runner/work/sof/sof/workspace/build-fuzz/zephyr/zephyr.exe 
: && /usr/bin/clang   zephyr/CMakeFiles/zephyr_pre0.dir/misc/empty_file.c.obj -o zephyr/zephyr.elf  zephyr/CMakeFiles/offsets.dir/./arch/posix/core/offsets/offsets.c.obj  -fuse-ld=bfd  -Wl,-T  zephyr/linker_zephyr_pre0.cmd  -Wl,-Map=/home/runner/work/sof/sof/workspace/build-fuzz/zephyr/zephyr_pre0.map  -Wl,--whole-archive  app/libapp.a  zephyr/libzephyr.a  zephyr/arch/arch/posix/core/libarch__posix__core.a  zephyr/soc/soc/posix/inf_clock/libsoc__posix__inf_clock.a  zephyr/boards/posix/native_posix/libboards__posix__native_posix.a  zephyr/drivers/console/libdrivers__console.a  zephyr/drivers/timer/libdrivers__timer.a  modules/sof/libmodules_sof.a  -Wl,--no-whole-archive  zephyr/kernel/libkernel.a  -L/home/runner/work/sof/sof/workspace/build-fuzz/zephyr  -Wl,--gc-sections  -Wl,--build-id=none  -Wl,--sort-common=descending  -Wl,--sort-section=alignment  --config  /home/runner/work/sof/sof/workspace/zephyr/cmake/toolchain/llvm/clang_libgcc.cfg  -Wl,-u,_OffsetAbsSyms  -Wl,-u,_ConfigAbsSyms  -Wl,-no-pie  -m32  -ldl  -pthread  -fsanitize=address,fuzzer  -lm && cd /home/runner/work/sof/sof/workspace/build-fuzz/zephyr && /usr/local/bin/cmake -E true && cd /home/runner/work/sof/sof/workspace/build-fuzz/zephyr && /usr/local/bin/cmake -E copy zephyr_pre0.map zephyr.map && /usr/bin/llvm-objdump -d zephyr.elf > zephyr.lst && /usr/bin/readelf -e zephyr.elf > zephyr.stat && /usr/bin/llvm-strip --strip-all zephyr.elf -ozephyr.strip && /usr/local/bin/cmake -E copy zephyr.elf zephyr.exe && /usr/bin/python3 /home/runner/work/sof/sof/workspace/zephyr/scripts/build/check_init_priorities.py --build-dir /home/runner/work/sof/sof/workspace/build-fuzz/zephyr/.. --edt-pickle /home/runner/work/sof/sof/workspace/build-fuzz/zephyr/edt.pickle
/usr/bin/ld.bfd: modules/sof/libmodules_sof.a(logging.c.obj): in function `ipc4_logging_shutdown':
/home/runner/work/sof/sof/workspace/sof/src/ipc/ipc4/logging.c:207: undefined reference to `ipc4_logging_enable_logs'
/usr/bin/ld.bfd: modules/sof/libmodules_sof.a(base_fw.c.obj): in function `basefw_set_large_config':
/home/runner/work/sof/sof/workspace/sof/src/audio/base_fw.c:462: undefined reference to `ipc4_logging_enable_logs'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake --build /home/runner/work/sof/sof/workspace/build-fuzz
Error: Process completed with exit code 1.
````

@kv2019i @lgirdwood  known issue?

**Comment by kv2019i** [comment]
@plbossart doh, that's my bad. this is a regression caused by https://github.com/thesofproject/sof/pull/8163 . let me file  a bug

**Review by ranj063 — APPROVED** [review]

**Comment by kv2019i** [comment]
Added @yongzhi1 , this would need to be checked on platform.

**Comment by plbossart** [comment]
> bclk_freq 256000/128000 and 1536000, can cardinal clk support above values?

24576000/256000 = 96
24576000/128000 = 192
24576000/1536000 = 16

all integer multiples so no issues.

What will not work is 2,400,000 Hz (10.24 ratio)

**Review by yongzhi1 — APPROVED** [review]

**Comment by yongzhi1** [comment]
> Added @yongzhi1 , this would need to be checked on platform.

@udaymb has verified above changes, thanks!!

**Review by kv2019i — APPROVED** [review]
