### PR TITLE
installer: add rpl and rpl-s aliases to tgl and tgl-h

### PR DESCRIPTION
**Pull request by marc-hb**
rpl firmware is tgl but signed with a different key

This commit adds the following files and links below
```
$ tree installer/staging/sof |
     grep -e tgl  -e rpl -e community |
     grep -v -e adl -e ehl

├── community
│   ├── sof-rpl.ri -> sof-tgl.ri
│   ├── sof-rpl-s.ri -> sof-tgl-h.ri
│   ├── sof-tgl-h.ri
│   └── sof-tgl.ri
├── sof-rpl.ldc -> sof-tgl.ldc
├── sof-rpl.ri -> intel-signed/sof-rpl.ri
├── sof-rpl-s.ldc -> sof-tgl-h.ldc
├── sof-rpl-s.ri -> intel-signed/sof-rpl-s.ri
├── sof-tgl-h.ldc
├── sof-tgl-h.ri -> intel-signed/sof-tgl-h.ri
├── sof-tgl.ldc
└── sof-tgl.ri -> intel-signed/sof-tgl.ri
```
Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]
Thanks @marc-hb !

**Review by plbossart — APPROVED** [review]
LGTM

**Comment by marc-hb** [comment]
@lyakh , @keqiaozhang any idea why https://github.com/thesofproject/sof/runs/7648620656 has failed with a missing debug/sparse.h ?


```
/workdir/src/audio/module_adapter/module/volume/volume_generic.c
In file included from /workdir/zephyr/../src/include/sof/audio/audio_stream.h:18,
                 from /workdir/zephyr/../src/include/sof/audio/buffer.h:11,
                 from /workdir/src/audio/module_adapter/module/volume/volume_generic.c:17:
/workdir/zephyr/../src/include/sof/compiler_attributes.h:11:10: fatal error: debug/sparse.h: No such file or directory
   11 | #include <debug/sparse.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

**Review by lgirdwood — APPROVED** [review]

**Comment by aiChaoSONG** [comment]
The zephyr-build failure is caused by https://github.com/zephyrproject-rtos/zephyr/commit/855216f582d2e10f65159c70f104579d0c6235b0. I tried to add the zephyr prefix like this `zephyr/debug/sparse.h`, but there are other failures.  so for SOF, we should select this config LEGACY_INCLUDE_PATH

**Comment by lgirdwood** [comment]
> The zephyr-build failure is caused by [zephyrproject-rtos/zephyr@855216f](https://github.com/zephyrproject-rtos/zephyr/commit/855216f582d2e10f65159c70f104579d0c6235b0). I tried to add the zephyr prefix like this `zephyr/debug/sparse.h`, but there are other failures. so for SOF, we should select this config LEGACY_INCLUDE_PATH

We should fix our code to align with Zephyr direction and not use LEGACY. @lyakh fyi.

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR6070/build1070/devicetest/ has only one unrelated suspend/resume issue, everything else is green. It successfully built Zephyr, most likely  because our internal check detected the ` LEGACY_INCLUDE_PATH=n` regression above and held onto older Zephyr commit da041942c286
