### ISSUE TITLE
[BUG] build error undefined reference to `__udivdi3 in mimx93_evk_a55 build

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#9129]
**Describe the bug**
Bug seen in SOF CI:
https://github.com/thesofproject/sof/actions/runs/9100439105/job/25015294155?pr=9125

Seems to be introduced in https://github.com/thesofproject/sof/pull/9090 -> @lyakh

**Comment by kv2019i** [comment]
FYI @marc-hb  filed as bug as this appears in all PR CI results.

**Comment by lgirdwood** [comment]
Can we close ?

**Comment by marc-hb** [comment]
No, as of today's commit 9c334976c4e0, `src/math/numbers.c` still has the  `#if !CONFIG_SOC_MIMX9352_A55` "merged to make the tests pass".

**Comment by lyakh** [comment]
@kv2019i this one should be good to close now
