### ISSUE TITLE
[BUG] [ADLP] invalid blob size for WoV detect_test

### ISSUE THREAD

**Issue by keyonjie** [thesofproject/sof#5007]
According to CI daily report, KWD feature doesn't work and check-keyword-detection.sh case fails on adlp-rvp-hda.

Initial analyze found that the failure happens at hw_param() and test_keyword_set_config() stage, the blob size is set to 2000 where it should be 0x20.

It works with both 1.9 and 1.8 FW.

**To Reproduce**
arecord -Dhw:sofhdadsp,7 -M -N --buffer-size=96000 -f s16_le -r 16000 -c 2 /dev/null -vvv

**Reproduction Rate**
100%.

**Expected behavior**
the blob size should be 0x20 and arecord should run.

**Impact**
KWD always fail and no WoV CI coverage for us anymore.

**Environment**
1) Kernel Branch: topic/sof-dev 2a6679fb
SOF Branch: main 8e7c07dd00ff

2) Name of the topology file
    * Topology: sof-hda-generic-4ch-kwd.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: adlp-rvp-hda

```
[        8464.739247] (         482.395813) c0 ipc                  src/ipc/ipc3/handler.c:1576 INFO ipc: new cmd 0x50030000
[        8485.624663] (          20.885416) c0 kd-test      12.72 ..../audio/detect_test.c:589  INFO test_keyword_cmd()
[        8503.749662] (          18.125000) c0 kd-test      12.72 ..../audio/detect_test.c:503  INFO test_keyword_cmd_set_data(), SOF_CTRL_CMD_BINARY
[        8523.072578] (          19.322916) c0 kd-test      12.72 ..../audio/detect_test.c:443  INFO test_keyword_set_config(), blob size = 2000
[        8546.822577] (          23.750000) c0 kd-test      12.72 ..../audio/detect_test.c:446  ERROR test_keyword_set_config(): invalid blob size
[        8569.478826] (          22.656250) c0 ipc                  src/ipc/ipc3/handler.c:1184 ERROR ipc: comp 72 cmd 3 failed -22
[        8737.864236] (         168.385406) c0 ipc                  src/ipc/ipc3/handler.c:1576 INFO ipc: new cmd 0x30020000
```

**Comment by keyonjie** [comment]
Looks this is not reproduced with latest main, let's close it for now.
