### ISSUE TITLE
[BUG] FW Compile error when enabling verbose spinlock debug

### ISSUE THREAD

**Issue by paulstelian97** [thesofproject/sof#2015]
**Describe the bug**

When selecting DEBUG and DEBUG_LOCKS_VERBOSE on the i.MX platform I get the following compile error:

```
[trimmed]/src/include/sof/spinlock.h:87:9: error: 'esai[i].lock' is a pointer; did you mean to use '->'?
   (lock)->user = __LINE__; \
```

(two times in my case, within the macro `spinlock_init`; I think dependent on platform this macro may be called a different number of times but I believe the error is actually not platform-specific)

**To Reproduce**
Steps to reproduce the behavior: (e.g. list commands or actions used to reproduce the bug)
* Generate default configuration: `make imx8_defconfig` (replace with your platform as I don't think this is platform specific)
* Select, in addition to the defconfig, DEBUG, DEBUG_LOCKS ~and DEBUG_LOCKS_VERBOSE~ (also occurs without selecting DEBUG_LOCKS_VERBOSE).
* Attempt build: `make -j8`

**Reproduction Rate**
100% (build error)

**Expected behavior**
Firmware should build successfully

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)
Annoyance

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: (doesn't matter)
    * SOF: 78b022bf (master)
2) Name of the platform(s) on which the bug is observed.
    * Platform: imx8 (though I believe this is not platform-specific)

**Comment by paulstelian97** [comment]
This issue was introduced with f7abaf7b; directly previous commit has different compile errors when I try to build it (`'struct comp_dev' has no member named 'lock'`, also within the same macro).
