### PR TITLE
ace: power policy management

### PR DESCRIPTION
**Pull request by tmleman**
List of changes:

- _custom power policy_: allows to override default power policy with application specific version,
- default prevent for all lower power states,
- add handlers to set/unset prevent on d0i3,
- enabling zephyr power management function for MTL.

### CODE REVIEW

**Review by marcinszkudlinski — APPROVED** [review]

File: src/lib-zephyr/cpu.c [hunk 1]
```diff
@@ -123,6 +123,7 @@ int cpu_enabled_cores(void)
 
 #else /* CONFIG_ACE */
 #include <sof/trace/trace.h>
+#include <rtos/wait.h>
```
Comment (kv2019i) [inline src/lib-zephyr/cpu.c:126]: The change is evident, but the commit leaves me wondering in which configuration? We have continuous build tests for ACE in SOF main, so in which configuration the build fails? 

If this is just to make code future-proof, better to reflect this in commit message.

**Review by kv2019i — COMMENTED** [review]
Looks good to go. One question @tmleman  is what is the build error patch and why it's in this series? The build is fine in current main, and I don't see other changes in cpu.c in this PR. So what is failing?

File: src/lib-zephyr/cpu.c (hunk 1 above)
Comment (lgirdwood) [reply src/lib-zephyr/cpu.c:126]: @kv2019i This could be needed as we de-tangle the rtos and generic headers. This will be ongoing and should be able to be completed after full native Zephyr mode is working upstream.

File: src/platform/intel/ace/lib/pm_runtime.c [hunk 2]
```diff
@@ -9,12 +9,56 @@
...
 
+#ifdef CONFIG_PM_POLICY_CUSTOM
+const struct pm_state_info *pm_policy_next_state(uint8_t cpu, int32_t ticks)
+{
+	uint8_t num_cpu_states;
+	const struct pm_state_info *cpu_states;
+
+	num_cpu_states = pm_state_cpu_get_all(cpu, &cpu_states);
+
+	for (int8_t i = num_cpu_states - 1; i >= 0; i--) {
```
Comment (lyakh) [inline src/platform/intel/ace/lib/pm_runtime.c:29]: `int` would be enough

File: src/platform/intel/ace/lib/pm_runtime.c [hunk 3]
```diff
@@ -9,12 +9,56 @@
...
 /* 76cc9773-440c-4df9-95a8-72defe7796fc */
 DECLARE_SOF_UUID("power", power_uuid, 0x76cc9773, 0x440c, 0x4df9,
 		 0x95, 0xa8, 0x72, 0xde, 0xfe, 0x77, 0x96, 0xfc);
 
 DECLARE_TR_CTX(power_tr, SOF_UUID(power_uuid), LOG_LEVEL_INFO);
 
+#ifdef CONFIG_PM_POLICY_CUSTOM
+const struct pm_state_info *pm_policy_next_state(uint8_t cpu, int32_t ticks)
+{
+	uint8_t num_cpu_states;
```
Comment (lyakh) [inline src/platform/intel/ace/lib/pm_runtime.c:24]: I see that `pm_state_cpu_get_all()` returns `uint8_t` but `unsigned int` would work here too

File: src/platform/intel/ace/lib/pm_runtime.c [hunk 4]
```diff
@@ -59,6 +60,40 @@ const struct pm_state_info *pm_policy_next_state(uint8_t cpu, int32_t ticks)
...
+static inline void ace_pm_runtime_allow_pgcg(bool enable)
+{
+	if (enable) {
+		pm_policy_state_lock_put(PM_STATE_RUNTIME_IDLE, PM_ALL_SUBSTATES);
+	} else {
+		pm_policy_state_lock_get(PM_STATE_RUNTIME_IDLE, PM_ALL_SUBSTATES);
+		/* Disable power gating when preventing */
+		DFDSPBRCP.bootctl[PLATFORM_PRIMARY_CORE_ID].bctl |=
+			DFDSPBRCP_BCTL_WAITIPCG | DFDSPBRCP_BCTL_WAITIPPG;
+	}
```
Comment (lyakh) [inline src/platform/intel/ace/lib/pm_runtime.c:72]: I'm not familiar with Zephyr PM API, are we safe here from `put()` or `get()` being unbalanced? I.e. can this function be called multiple times with the same value of `enable`?

File: src/platform/intel/ace/lib/pm_runtime.c [hunk 5]
```diff
@@ -59,6 +60,40 @@ const struct pm_state_info *pm_policy_next_state(uint8_t cpu, int32_t ticks)
...
+}
+
+void platform_pm_runtime_enable(uint32_t context, uint32_t index)
+{
+	switch (context) {
+	case PM_RUNTIME_DSP:
+		ace_pm_runtime_allow_pgcg(true);
```
Comment (lyakh) [inline src/platform/intel/ace/lib/pm_runtime.c:79]: sorry, I don't think this makes much sense. `ace_pm_runtime_allow_pgcg()` shares ZERO code between `true` and `false` cases. You make those cases into the same function with a parameter, then it's called from two locations - both with that parameter fixed to a constant. Why not just do what has to be done here and in `disable()` below directly?

File: src/platform/intel/ace/lib/pm_runtime.c (hunk 4 above)
Comment (tmleman) [reply src/platform/intel/ace/lib/pm_runtime.c:72]: Functions can be called multiple times but to balance the count of it is on the application side.

**Review by lgirdwood — APPROVED** [review]
@tmleman would be nice to have some more inline comments around the state logic i.e. explaining the policy and how we change state but that can be added later. Lets get this integrated and tested first.

File: zephyr/wrapper.c [hunk 6]
```diff
@@ -624,7 +625,10 @@ int task_main_start(struct sof *sof)
 	 * (only called from single core, no RMW lock)
 	 */
 	__ASSERT_NO_MSG(cpu_get_id() == PLATFORM_PRIMARY_CORE_ID);
-
+#if defined(CONFIG_PM)
```
Comment (abonislawski) [inline zephyr/wrapper.c:628]: Better to stay with one version of ifdef
#if defined(CONFIG_PM)
#ifdef CONFIG_PM_POLICY_CUSTOM

**Review by abonislawski — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]

**Review by aborisovich — APPROVED** [review]

**Comment by lgirdwood** [comment]
@tmleman like we have a build error on MTL in CI for GCC config.

**Comment by lgirdwood** [comment]
@tmleman still seeing an error
```
/zep_workspace/sof/src/audio/up_down_mixer/up_down_mixer.c
/zep_workspace/sof/src/audio/up_down_mixer/up_down_mixer.c: In function 'up_down_mixer_new':
/zep_workspace/sof/src/audio/up_down_mixer/up_down_mixer.c:423:39: error: passing argument 2 of 'init_up_down_mixer' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  423 |         ret = init_up_down_mixer(dev, config, spec);
      |                                       ^~~~~~
/zep_workspace/sof/src/audio/up_down_mixer/up_down_mixer.c:340:77: note: expected 'struct comp_ipc_config *' but argument is of type 'const struct comp_ipc_config *'
  340 | static int init_up_down_mixer(struct comp_dev *dev, struct comp_ipc_config *config, void *spec)
      |                                                     ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/zep_workspace/sof/src/audio/up_down_mixer/up_down_mixer.c:423:47: error: passing argument 3 of 'init_up_down_mixer' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  423 |         ret = init_up_down_mixer(dev, config, spec);
      |                                               ^~~~
/zep_workspace/sof/src/audio/up_down_mixer/up_down_mixer.c:340:91: note: expected 'void *' but argument is of type 'const void *'
  340 | static int init_up_down_mixer(struct comp_dev *dev, struct comp_ipc_config *config, void *spec)
      |                                                                                     ~~~~~~^~~~
```

**Comment by kv2019i** [comment]
@lgirdwood wrote:
> @tmleman still seeing an error
> 
> ```
> /zep_workspace/sof/src/audio/up_down_mixer/up_down_mixer.c
> /zep_workspace/sof/src/audio/up_down_mixer/up_down_mixer.c: In function 'up_down_mixer_new':
> /zep_workspace/sof/src/audio/up_down_mixer/up_down_mixer.c:423:39: error: passing argument 2 of 

That's caused by https://github.com/thesofproject/sof/pull/6517 that was merged yesterday. My bad, should have caught this pre-merge. Let's address this in a separate PR.

**Comment by kv2019i** [comment]
Known failures in CI. I did a local test with Zephyr SDK toolchain and all passes cleanly now. Proceeding with merge.
