### ISSUE TITLE
[BUG]underrun and ipc timed out when multiple-pause-resume on CML_HEL_RT5682

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/sof#4561]
**Describe the bug**
in inner daily   5539?model=CML_HEL_RT5682&testcase=multiple-pause-resume-25
underrun happened when multiple-pau-resume and xrun recovery failed , ipc timed out  also
can reproduce it
**To Reproduce**
 TPLG=/lib/firmware/intel/sof-tplg/sof-cml-rt1011-rt5682.tplg ~/sof-test/test-case/multiple-pause-resume.sh -r 25

**Environment**
Kernel Branch: topic/sof-dev
Kernel Commit: 85bfa34a
SOF Branch: main
SOF Commit: 9a7a5ce17dcb
 Topology:sof-cml-rt1011-rt5682.tplg 
Platform:CML_HEL_RT5682

**Screenshots or console output**
[dmesg]
```
[ 4875.459281] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x60060000: GLB_STREAM_MSG: TRIG_PAUSE
[ 4875.459585] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx succeeded: 0x60060000: GLB_STREAM_MSG: TRIG_PAUSE
[ 4875.459628] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x160]=0x20140000 successful
[ 4875.460011] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 4
[ 4875.460574] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x160]=0x2014001e successful
[ 4875.460600] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x60070000: GLB_STREAM_MSG: TRIG_RELEASE
[ 4875.599462] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: pcm: trigger stream 5 dir 0 cmd 3
[ 4875.726745] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 4875.726823] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 4875.966715] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: error: ipc timed out for 0x60070000 size 12
[ 4875.966756] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: preventing DSP entering D3 state to preserve context
[ 4875.966769] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ------------[ IPC dump start ]------------
[ 4875.966804] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000181 rirb 00
[ 4875.966824] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[ 4875.966852] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[ 4875.966869] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ------------[ IPC dump end ]------------
[ 4875.966883] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ------------[ DSP dump start ]------------
[ 4875.966904] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: status: fw entered - code 00000005
[ 4875.967313] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[ 4875.967332] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ------------[ DSP dump end ]------------
[ 4875.967378] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -110
[ 4875.967399] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: error: trace IO error
```
[etrace]
```
detected
[    52698087.905966] (      315000.718750) c0 dma-trace          ..../intel/hda/hda-dma.c:861  ERROR hda_dma_link_check_xrun(): underrun detected
[    52977432.894866] (      279345.000000) c0 dma-trace                    src/lib/wait.c:46   ERROR poll timeout reg 487496 mask 63 val 0 us 937
[    54617146.996376] (     1639714.125000) c0 dma-trace              src/drivers/dw/dma.c:1102 ERROR dw_dma_get_data_size(): xrun detected
[    54617160.954709] (          13.958333) c0 dma-trace                   src/audio/dai.c:886  ERROR dai_report_xrun(): underrun due to no data available
[    54617174.652625] (          13.697916) c0 dma-trace                   src/audio/dai.c:675  ERROR comp_underrun(): dev->comp.id = 4, source->avail = 192, copy_bytes = 0
[    54617188.975541] (          14.322916) c0 dma-trace          ....../pipeline-stream.c:307  ERROR pipeline_trigger_run(): ret = -22, host->comp.id = 0, cmd = 8
[    54617202.204707] (          13.229166) c0 dma-trace          ......../pipeline-xrun.c:159  ERROR pipeline_xrun(): Pipelines notification about XRUN failed, ret = -22
[    54617229.131790] (          26.927082) c0 dma-trace          ....../pipeline-stream.c:194  ERROR pipeline_copy(): ret = -61, start->comp.id = 4, dir = 1
[    54617242.204706] (          13.072916) c0 dma-trace          ..../pipeline-schedule.c:95   ERROR pipeline_task(): xrun recovery failed! pipeline is stopped.
[    61038022.418317] (     6420780.000000) c0 dma-trace              src/drivers/dw/dma.c:1102 ERROR dw_dma_get_data_size(): xrun detected
[    61038035.543316] (          13.124999) c0 dma-trace                   src/audio/dai.c:886  ERROR dai_report_xrun(): underrun due to no data available
[    61038048.147483] (          12.604166) c0 dma-trace                   src/audio/dai.c:675  ERROR comp_underrun(): dev->comp.id = 38, source->avail = 0, copy_bytes = 0
[    61038061.793315] (          13.645833) c0 dma-trace          ....../pipeline-stream.c:307  ERROR pipeline_trigger_run(): ret = -22, host->comp.id = 34, cmd = 8
[    61038075.230815] (          13.437499) c0 dma-trace          ......../pipeline-xrun.c:159  ERROR pipeline_xrun(): Pipelines notification about XRUN failed, ret = -22
[    61038102.782897] (          27.552082) c0 dma-trace          ....../pipeline-stream.c:194  ERROR pipeline_copy(): ret = -61, start->comp.id = 38, dir = 1
[    61038116.064147] (          13.281249) c0 dma-trace          ..../pipeline-schedule.c:95   ERROR pipeline_task(): xrun recovery failed! 
```

**Comment by ranj063** [comment]
this was introduced by https://github.com/thesofproject/sof/commit/9a7a5ce17dcb too. @lyakh FYI

**Comment by lgirdwood** [comment]
Looks to be the same cause as #4560, potentially spinning with IRQs OFF (but this time a lot longer).

**Comment by XiaoyunWu6666** [comment]
Close it now since relevant feature was reverted in #4578
