### PR TITLE
west.yml: update Zephyr to 492517b918d26

### PR DESCRIPTION
**Pull request by dbaluta**
Contains 700+ commits, including following directly affecting SOF with i.MX:

492517b918 west.yml: Update NXP HAL SDK to 2.14

It also pulls in following commits affecting SOF targets:

a5d1fd9857 soc: adsp: clk: update clock switch flow
9656056b19 dts: adsp: ace20: remove lp clock
50f0e223e8 dts: adsp: ace15: remove lp clock
cf6d5f95b6 adsp: clk: ace: select ipll if wovrco is unavailable
2d835e1b29 dts: adsp: ace20: replace hp with ipll clock
dcecda859c dts: adsp: ace15: replace hp with ipll clock
2f2689e3d3 intel_adsp: ace15: shim: update wovrco request bit

### CODE REVIEW

**Comment by dbaluta** [comment]
Looks like MTL build fails for zephyr. 

Sent the following PR to fix it: https://github.com/zephyrproject-rtos/zephyr/pull/62854

Also, I think we should upgrade zephyr main at least once a week to avoid pulling too many changes at once.

**Review by tmleman — COMMENTED** [review]
I'm doing the same thing here https://github.com/thesofproject/sof/pull/8182

But first, I think we need to integrate this https://github.com/thesofproject/sof/pull/8212

**Comment by kv2019i** [comment]
@tmleman @dbaluta Is it ok we merge first the PR that gets a clean CI pass? I don't think we need to wait for #8212 (I don't see a hard dependency), but #8182 is not passing yet. We've had some transient issues (network issues resulting in failures) in CI, but it is possible we have some regression with upstream Zephyr, so we need to check the results carefully.

**Comment by dbaluta** [comment]
@kv2019i @dbaluta  let the PR war begin :).

Yes, let's try to coordinate and merge a zephyr update that works for everyone.

**Comment by dbaluta** [comment]
> But first, I think we need to integrate this #8212

I don't think we need to integrate https://github.com/thesofproject/sof/pull/8212 first, it it takes too long to review it. 

I'm more concerned now about the zephyr update which seems to be causing some troubles.

**Comment by tmleman** [comment]
> I don't think we need to wait for #8212 (I don't see a hard dependency)

@kv2019i from what I know there made changes in internal CI for https://github.com/thesofproject/sof/pull/8212 and in my PR TGL is failing, coincidence?

@wszypelt can you confirm this

**Comment by wszypelt** [comment]
> > I don't think we need to wait for #8212 (I don't see a hard dependency)
> 
> @kv2019i from what I know there made changes in internal CI for #8212 and in my PR TGL is failing, coincidence?
> 
> @wszypelt can you confirm this

@tmleman @dbaluta @kv2019i 
I confirm that the errors that occurred were caused by changes in the Internal Intel CI service so that PR 8212 could run correctly. For now, I have reverted the changes I made to the Internal Intel CI service so that this and other PRs can run properly.

**Comment by marc-hb** [comment]
> We do have some sparse warnings that are frightening me.

Indeed. It is triggered by this PR because the sparse daily build looks OK:
https://github.com/thesofproject/sof/actions/workflows/daily-tests.yml

Please save the links, they can be hard to find after force-pushes (yet another sign Github does not like force pushes)

https://github.com/thesofproject/sof/actions/runs/6247162197/job/16959223474?pr=8235

```
/zep_workspace/zephyr/lib/os/printk.c:123:33: error: undefined identifier 'FDEV_SETUP_STREAM'
/zep_workspace/zephyr/lib/os/printk.c:144:32: error: undefined identifier 'FDEV_SETUP_STREAM'
/zep_workspace/zephyr/lib/os/printk.c:144:49: error: invalid initializer
/zep_workspace/zephyr/include/zephyr/posix/sys/stat.h:40:11: error: unable to open 'sys/_timespec.h'
```

**Comment by marc-hb** [comment]
Sparse failure bisected to the switch to PICOLIBC:
- https://github.com/zephyrproject-rtos/zephyr/issues/63003

`CONFIG_MINIMAL_LIBC=y` in an overlay should be enough to avoid it.

**Comment by kv2019i** [comment]
@dbaluta @tmleman We need https://github.com/thesofproject/sof/pull/8255 to fix the sparse and then we are ready to update the Zephyr baseline.

**Comment by dbaluta** [comment]
@kv2019i im on vacation this week. @tmleman can you help?

**Comment by tmleman** [comment]
> @kv2019i im on vacation this week. @tmleman can you help?

ACK

**Comment by iuliana-prodan** [comment]
> > @kv2019i im on vacation this week. @tmleman can you help?
> 
> ACK

Can somebody merge https://github.com/thesofproject/sof/pull/8255?
And next we can check this as @kv2019i said above.

**Comment by iuliana-prodan** [comment]
SOFCI TEST

**Comment by iuliana-prodan** [comment]
@kv2019i how can we trigger the CI?
Since https://github.com/thesofproject/sof/pull/8255 was merged I'm expecting some  CI checks to pass.

**Comment by lgirdwood** [comment]
> @kv2019i how can we trigger the CI? Since #8255 was merged I'm expecting some CI checks to pass.

I think this will need a rebase and force push, newer PRs passing. Any other dependecies before merging this ?

**Comment by iuliana-prodan** [comment]
> @iuliana-prodan can you please create a PR with this update. will close mine as i'm not really able to update it on the phon3 :)

https://github.com/thesofproject/sof/pull/8264

**Comment by marc-hb** [comment]
> I think this will need a rebase and force push,

Unless there are conflicts rebase is never required (and discouraged byhttps://docs.zephyrproject.org/latest/contribute/contributor_expectations.html#workflow-suggestions-that-help-reviewers)

`git commit --amend -C HEAD` to change the commit date + force push is enough.

Just FYI.

**Comment by kv2019i** [comment]
@iuliana-prodan @dbaluta @tmleman is working on an update in https://github.com/thesofproject/sof/pull/8182 
Unfortunately there is now some new regression. Tests on Intel MTL are failing with latest Zephyr while they pass with current manfiest versions. @tmleman is following up with this.
