### PR TITLE
kpb: fix kpb reset issue to make the consequent iteration work

### PR DESCRIPTION
**Pull request by keyonjie**
We need reset kpb->state to KPB_STATE_BUFFERING, and unregister notifier
in .reset() as we will register it again at next .prepare(), otherwise,
the consequent record won't work.

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

### CODE REVIEW

File: src/audio/kpb.c [hunk 1]
```diff
@@ -431,12 +431,17 @@ static int kpb_reset(struct comp_dev *dev)
...
 
+	/* Reset state to be buffering */
+	kpb->state = KPB_STATE_BUFFERING;
 	/* Reset history buffer */
 	kpb->is_internal_buffer_full = false;
 	kpb_clear_history_buffer(kpb->history_buffer);
 	/* Reset amount of buffered data */
 	kpb->buffered_data = 0;
 
+	/* unregister KPB for async notification */
```
Comment (mrajwa) [inline src/audio/kpb.c]: Maybe start comment from capital letter as other comments inside KPB.

Comment (keyonjie) [reply src/audio/kpb.c]: sure, let me change it.

**Comment by jajanusz** [comment]
@keyonjie Please fix UT, there is just minor problem with some missing reference

**Comment by keyonjie** [comment]
> @keyonjie Please fix UT, there is just minor problem with some missing reference

@jajanusz it's quite strange to me that it keep reporting errors like this even after I #include <sof/notifier.h> :

```
CMakeFiles/kpb.dir/__/__/__/__/__/src/audio/kpb.c.o: In function `kpb_prepare':
/home/keyon/hdd/github/keyonjie/sof/src/audio/kpb.c:350: undefined reference to `notifier_unregister'
/home/keyon/hdd/github/keyonjie/sof/src/audio/kpb.c:372: undefined reference to `notifier_unregister'
```

**Comment by keyonjie** [comment]
@jajanusz can you help on this please, it looks the kpb UT is missing some libraries, you are expert of it.

**Comment by jajanusz** [comment]
> @jajanusz can you help on this please, it looks the kpb UT is missing some libraries, you are expert of it.

Sure, I'll paste it here instead of doing PR to your branch, to not break git bisect for UT within multiple commits.
You used function that is not linked to test binary, it's easier to just create stub. 
Just add it: 
```diff
diff --git a/test/cmocka/src/audio/kpb/kpb_mock.c b/test/cmocka/src/audio/kpb/kpb_mock.c
index fcc768a2..6622aad8 100644
--- a/test/cmocka/src/audio/kpb/kpb_mock.c
+++ b/test/cmocka/src/audio/kpb/kpb_mock.c
@@ -45,6 +45,10 @@ void notifier_register(struct notifier *notifier)
 {
 }

+void notifier_unregister(struct notifier *notifier)
+{
+}
+
 int schedule_task_init(struct task *task, uint16_t type, uint16_t priority,
                       uint64_t (*func)(void *data), void *data, uint16_t core,
                       uint32_t xflags)
```

**Comment by jajanusz** [comment]
> > @keyonjie Please fix UT, there is just minor problem with some missing reference
> 
> @jajanusz it's quite strange to me that it keep reporting errors like this even after I #include <sof/notifier.h> :
> 
> ```
> CMakeFiles/kpb.dir/__/__/__/__/__/src/audio/kpb.c.o: In function `kpb_prepare':
> /home/keyon/hdd/github/keyonjie/sof/src/audio/kpb.c:350: undefined reference to `notifier_unregister'
> /home/keyon/hdd/github/keyonjie/sof/src/audio/kpb.c:372: undefined reference to `notifier_unregister'
> ```

FYI: #include just makes compiler aware of the symbol, and that there is *somewhere* - but code for that function didn't get built and linked into binary so it failed in linking step

**Comment by keyonjie** [comment]
Make sense @jajanusz, thank you.

**Comment by keyonjie** [comment]
@jajanusz updated.

**Comment by jajanusz** [comment]
@keyonjie as I wrote you should have it in 1 commit to not break git bisect for unit tests. The change to functionality and update to unit tests should be in the same commit.

**Comment by keyonjie** [comment]
> @keyonjie as I wrote you should have it in 1 commit to not break git bisect for unit tests. The change to functionality and update to unit tests should be in the same commit.

@jajanusz I added UT function notifier_unregister in the first patch and used it in the later commit, this shouldn't break any bisection?

Anyway, I can merge them if that looks better to you.

**Comment by keyonjie** [comment]
@jajanusz updated.
