### PR TITLE
ipc: idc: Fix dpmodule delete operation for multicore pipeline

### PR DESCRIPTION
**Pull request by jxstelter**
With DP modules introduction we got possibility to have modules assigned to given pipeline
but executed on different core to the pipeline core. In that situation the delete pipeline operations
omits such module leaving it allocated after pipeline removal.
This PR fix this issue.

Jaroslaw Stelter <Jaroslaw.Stelter@intel.com>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
LGTM @jxstelter I guess we are still waiting results from testing ?

File: src/ipc/ipc4/handler.c [hunk 1]
```diff
@@ -568,7 +568,7 @@ static int ipc4_set_pipeline_state(struct ipc4_message_request *ipc4)
 
 	/* Run the prepare phase on the pipelines */
 	for (i = 0; i < ppl_count; i++) {
-		ppl_icd = ipc_get_comp_by_ppl_id(ipc, COMP_TYPE_PIPELINE, ppl_id[i]);
+		ppl_icd = ipc_get_comp_by_ppl_id(ipc, COMP_TYPE_PIPELINE, ppl_id[i], true);
```
Comment (kv2019i) [inline src/ipc/ipc4/handler.c:571]: Hmm, boolean args have an impact to readability of the calling code. Given this is used in a lot of places, I'd prefer to add named defined/enum (IPC_COMP_ALL and IPC_COMP_IGNORE_REMOTE) and then have more readable code at the calling function:

```
ipc_get_comp_by_ppl_id(ipc, COMP_TYPE_PIPELINE, ppl_id[i], IPC_COMP_IGNORE_REMOTE);`

ipc_get_comp_by_ppl_id(ipc, COMP_TYPE_PIPELINE, ppl_id[i], IPC_COMP_ALL);
```

**Review by kv2019i — APPROVED** [review]
I have a code style preference to avoid booleans like this, but I won't block a merge. Please consider my proposal inline.

File: src/ipc/ipc4/handler.c (hunk 1 above)
Comment (jxstelter) [reply src/ipc/ipc4/handler.c]: Changed according to Kai suggestion.

**Review by RanderWang — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@jxstelter can you check CI, some failures/results not in. Thanks !

**Comment by lgirdwood** [comment]
Although, this looks unrelated
```
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake --build /home/runner/work/sof/sof/workspace/build-fuzz
/usr/bin/ld.bfd: modules/sof/libmodules_sof.a(smart_amp_test_ipc3.c.obj): in function `sys_comp_smart_amp_init':
/home/runner/work/sof/sof/workspace/sof/src/samples/audio/smart_amp_test_ipc3.c:559: multiple definition of `sys_comp_smart_amp_init'; modules/sof/libmodules_sof.a(smart_amp.c.obj):/home/runner/work/sof/sof/workspace/sof/src/audio/smart_amp/smart_amp.c:828: first defined here
/usr/bin/ld.bfd: modules/sof/libmodules_sof.a(smart_amp_test_ipc3.c.obj):/home/runner/work/sof/sof/workspace/sof/src/samples/audio/smart_amp_test_ipc3.c:24: multiple definition of `smart_amp_comp_uuid'; modules/sof/libmodules_sof.a(smart_amp.c.obj):/home/runner/work/sof/sof/workspace/sof/src/audio/smart_amp/smart_amp.c:25: first defined here
/usr/bin/ld.bfd: modules/sof/libmodules_sof.a(smart_amp_test_ipc3.c.obj):/home/runner/work/sof/sof/workspace/sof/src/samples/audio/smart_amp_test_ipc3.c:27: multiple definition of `smart_amp_comp_tr'; modules/sof/libmodules_sof.a(smart_amp.c.obj):/home/runner/work/sof/sof/workspace/sof/src/audio/smart_amp/smart_amp.c:34: first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
@kv2019i have you seen this ?

**Comment by kv2019i** [comment]
@lgirdwood Yes, this is a regression from this week, potentially two PRs merged at the same time.

**Review by marcinszkudlinski — APPROVED** [review]

**Comment by kv2019i** [comment]
@jxstelter This is ready to be merged, just waiting for clean CI run of mandatory checks.

**Comment by jxstelter** [comment]
> @jxstelter This is ready to be merged, just waiting for clean CI run of mandatory checks.

CI passed.
