### PR TITLE
testbench: fix a bug, leading to a build failure

### PR DESCRIPTION
**Pull request by lyakh**
Building testbench is broken, due to a missing "extern." Please also cherry-pick to 1.6

### CODE REVIEW

**Comment by lyakh** [comment]
maybe in fact this fix is wrong and the variable should be `static` instead

**Comment by marc-hb** [comment]
can you please share the output of this "nm" command below and also your /usr/bin/ld --version and cc --version?

To be sure which compiler is used on your  system look at the output of:
```
 make -C tools/testbench/build_testbench/ VERBOSE=anything clean testbench

nm tools/testbench/build_testbench/CMakeFiles/testbench.dir/topology.c.o | grep table
0000000000000008 C lib_table
```
https://sourceware.org/binutils/docs/ld/Options.html, look at "--warn-common"


You should get at worst a warning, a fatal linker error still does not make sense.
The testbench has been successfully built _and run_ in every CI PR for months:
https://travis-ci.org/github/thesofproject/sof/builds/

Something does not add up, there is an unknown issue.

**Review by marc-hb — CHANGES_REQUESTED** [review]
Not requesting changes but more investigation.

BTW Travis has been a zombie for a week with no end in sight:
https://travis-ci.community/t/builds-hang-in-queued-state/10250

**Comment by lyakh** [comment]
@marc-hb here's the answer: https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common yes, I've got gcc-10

**Review by marc-hb — CHANGES_REQUESTED** [review]
Thanks @lyakh for helping solve the mystery! I can very easily reproduce locally now with just this: `CFLAGS=-fno-common ./scripts/rebuild-testbench.sh `

The commit message is not there, it doesn't even have the word "common" once. It should also explain how this was even working before. I provided such an explanation in the commit message of my alternative, `extern` #3575 fix for this.

I'm really not a fan of having two different, top-level `lib_table` symbols in two different files that have the exact same name and need to be "synchronized" at run time somewhere buried in the `parse_topology()` function. This all took me an IMHO unreasonable time to figure out.

#3575 is a bit longer but it makes the lib_table `extern` and actually global and `shared_` instead of `static` which I think was the original idea, @ranj063 can you confirm?

**Comment by cujomalainey** [comment]
This might become a mute problem in near future. I am working to refactor the library build system and move it to be as close as possible to the regular firmware build system and one of my targets is fixing the fact that the components are built independently and linked in the library build but not in the firmware build.

**Comment by marc-hb** [comment]
> This might become a mute problem in near future. 

I'm not sure what problem exactly, could you be more specific?

>  built independently and linked in the library build but not in the firmware build.

Sorry to ask more of your time again but would you have some example of "components not built independently" in the firmware?


BTW I wonder whether we should add `CFLAGS=-fno-common` to the default testbench build, seems like a good flag to me.

**Comment by cujomalainey** [comment]
> > This might become a mute problem in near future.
> 
> I'm not sure what problem exactly, could you be more specific?

The duplicate symbols. I am working to dedup a lot of the code in host builds.
> 
> > built independently and linked in the library build but not in the firmware build.
> 
> Sorry to ask more of your time again but would you have some example of "components not built independently" in the firmware?

When we do a host build right now we treat [each component as a library](https://github.com/thesofproject/sof/blob/master/src/audio/CMakeLists.txt#L88) which results in some host specific build failures. I am sure bugs like this duplicate symbol issue slip through because of the non-unified build flow.
> 
> BTW I wonder whether we should add `CFLAGS=-fno-common` to the default testbench build, seems like a good flag to me.

**Comment by lgirdwood** [comment]
@cujomalainey do you have an ETA for update or should @lyakh unify with a single lib_table here ? Btw, where are the other defs or users of this ?

**Comment by lgirdwood** [comment]
ok I now see #3575 - @cujomalainey @lyakh any comments on here. We can close this if needed.

**Comment by cujomalainey** [comment]
The fix can go in, my timeline is unstable right now

**Comment by marc-hb** [comment]
> When we do a host build right now we treat each component as a library 

Mmmm... is this also why when running make twice back to back, the second make is as verbose as the first one, making incremental build output totally unreadable?

**Comment by cujomalainey** [comment]
> > When we do a host build right now we treat each component as a library
> 
> Mmmm... is this also why when running make twice back to back, the second make is as verbose as the first one, making incremental build output totally unreadable?

Not sure, don't know enough about (c)make to make that assertion. My planned fix is to compile all the files into the build (like the firmware) but add the preprocessor defines based on the tests we are currently using to select the files to compile.

**Comment by lyakh** [comment]
> ok I now see #3575 - @cujomalainey @lyakh any comments on here. We can close this if needed.

@lgirdwood sure, either of these fixes the bug, I've approved Marc's PR
